export const HOLIDAY_DESCS = [
  {
    key: "",
    subKey: "",
    date: 0,
    start: 0,
    desc: "",
    link: "",
  },
  {
    key: "元日",
    subKey: "",
    date: 101,
    start: 0,
    desc: "新年を迎える年の最初の日。日付はグレゴリオ暦では1月1日（日本の改暦前、太陰太陽暦では旧暦の正月一日）。元旦（がんたん）ともいうが、この場合は特にその日の朝を指すこともある",
    link: "https://ja.wikipedia.org/wiki/%E5%85%83%E6%97%A5"
  },
  {
    key: "成人の日",
    subKey: "",
    date: "",
    start: "",
    desc: "「おとなになったことを自覚し、みずから生き抜こうとする青年を祝いはげます」ことを趣旨としている。",
    link: "https://ja.wikipedia.org/wiki/%E6%88%90%E4%BA%BA%E3%81%AE%E6%97%A5",
  },
  {
    key: "建国記念日",
    subKey: "",
    date: 211,
    start: 1967,
    desc: "日付は政令に基づき、建国神話（日本神話）を基に日本建国日とされている旧紀元節と同じ日にされた。",
    link: "https://ja.wikipedia.org/wiki/%E5%BB%BA%E5%9B%BD%E8%A8%98%E5%BF%B5%E3%81%AE%E6%97%A5",
  },
  {
    key: "天皇誕生日",
    subKey: "令和",
    date: 223,
    start: 2019,
    desc: "第126代天皇徳仁の誕生日である2月23日（2020年〈令和2年〉以降）",
    link: "https://ja.wikipedia.org/wiki/%E5%A4%A9%E7%9A%87%E8%AA%95%E7%94%9F%E6%97%A5"
  },
  {
    key: "天皇誕生日",
    subKey: "平成",
    date: 1223,
    start: 1989,
    desc: "第125代天皇明仁の誕生日である12月23日（1989年〈平成元年〉以降）",
    link: "https://ja.wikipedia.org/wiki/%E5%A4%A9%E7%9A%87%E8%AA%95%E7%94%9F%E6%97%A5"
  },
  {
    key: "天皇誕生日",
    subKey: "昭和",
    date: 429,
    start: 1949,
    desc: "第124代天皇裕仁の誕生日である4月29日（2020年〈令和2年〉以降）",
    link: "https://ja.wikipedia.org/wiki/%E5%A4%A9%E7%9A%87%E8%AA%95%E7%94%9F%E6%97%A5"
  },
  {
    key: "春分の日",
    subKey: "",
    date: 0,
    start: 0,
    desc: "しばしば昼が長くなって「昼と夜の長さが等しくなる日」といわれるが、実際は昼の方が少し長い。詳細は春分を参照。",
    link: "https://ja.wikipedia.org/wiki/%E6%98%A5%E5%88%86%E3%81%AE%E6%97%A5",
  },
  {
    key: "昭和の日",
    subKey: "",
    date: 429,
    start: 0,
    desc: "「激動の日々を経て、復興を遂げた昭和の時代を顧（かえり）み、国の将来に思いをいたす」",
    link: "https://ja.wikipedia.org/wiki/%E6%98%AD%E5%92%8C%E3%81%AE%E6%97%A5",
  },
  {
    key: "憲法記念日",
    subKey: "",
    date: 503,
    start: 0,
    desc: "「日本国憲法の施行を記念し、国の成長を期する」ことを趣旨としている",
    link: "https://ja.wikipedia.org/wiki/%E6%86%B2%E6%B3%95%E8%A8%98%E5%BF%B5%E6%97%A5_(%E6%97%A5%E6%9C%AC)",
  },
  {
    key: "みどりの日",
    subKey: "",
    date: 504,
    start: 0,
    desc: "「自然に親しむとともにその恩恵に感謝し、豊かな心を育む」ことを趣旨とする。ゴールデンウィークを構成する休日の一つである。",
    link: "https://ja.wikipedia.org/wiki/%E3%81%BF%E3%81%A9%E3%82%8A%E3%81%AE%E6%97%A5",
  },
  {
    key: "こどもの日",
    subKey: "",
    date: 505,
    start: 0,
    desc: "「こどもの人格を重んじ、こどもの幸福をはかるとともに、母に感謝する」ことが趣旨である。",
    link: "https://ja.wikipedia.org/wiki/%E3%81%93%E3%81%A9%E3%82%82%E3%81%AE%E6%97%A5",
  },
  {
    key: "海の日",
    subKey: "",
    date: 0,
    start: 0,
    desc: "「海の恩恵に感謝するとともに、海洋国日本の繁栄を願う」ことを趣旨としている。",
    link: "https://ja.wikipedia.org/wiki/%E6%B5%B7%E3%81%AE%E6%97%A5",
  },
  {
    key: "山の日",
    subKey: "",
    date: 811,
    start: 0,
    desc: "「山に親しむ機会を得て、山の恩恵に感謝する」ことを趣旨としている。",
    link: "https://ja.wikipedia.org/wiki/%E5%B1%B1%E3%81%AE%E6%97%A5",
  },
  {
    key: "敬老の日",
    subKey: "",
    date: 0,
    start: 0,
    desc: "「多年にわたり社会につくしてきた老人を敬愛し、長寿を祝う」ことを趣旨としている。",
    link: "https://ja.wikipedia.org/wiki/%E6%95%AC%E8%80%81%E3%81%AE%E6%97%A5",
  },
  {
    key: "秋分の日",
    subKey: "",
    date: 0,
    start: 0,
    desc: "「祖先をうやまい、なくなった人々をしのぶ。」ことを趣旨としている。",
    link: "https://ja.wikipedia.org/wiki/%E7%A7%8B%E5%88%86%E3%81%AE%E6%97%A5",
  },
  {
    key: "スポーツの日",
    subKey: "",
    date: 0,
    start: 0,
    desc: "「スポーツを楽しみ、他者を尊重する精神を培うとともに、健康で活力ある社会の実現を願う。」",
    link: "https://ja.wikipedia.org/wiki/%E3%82%B9%E3%83%9D%E3%83%BC%E3%83%84%E3%81%AE%E6%97%A5_(%E6%97%A5%E6%9C%AC)",
  },
  {
    key: "文化の日",
    subKey: "",
    date: 1103,
    start: 0,
    desc: "「自由と平和を愛し、文化をすすめる」ことを趣旨としている。",
    link: "https://ja.wikipedia.org/wiki/%E6%96%87%E5%8C%96%E3%81%AE%E6%97%A5",
  },
  {
    key: "勤労感謝の日",
    subKey: "",
    date: 1123,
    start: 0,
    desc: "「勤労をたつとび、生産を祝い、国民がたがいに感謝しあう」ことを趣旨としている。",
    link: "https://ja.wikipedia.org/wiki/%E5%8B%A4%E5%8A%B4%E6%84%9F%E8%AC%9D%E3%81%AE%E6%97%A5",
  },
  {
    key: "体育の日",
    subKey: "",
    date: 0,
    start: 0,
    desc: "1964年（昭和39年）に東京オリンピックの開会式が行われた10月10日を、1966年（昭和41年）に「体育の日」に定め国民の祝日とした。",
    link: "https://ja.wikipedia.org/wiki/%E3%82%B9%E3%83%9D%E3%83%BC%E3%83%84%E3%81%AE%E6%97%A5_(%E6%97%A5%E6%9C%AC)",
  },
  {
    key: "天皇の即位の日",
    subKey: "",
    date: 0,
    start: 0,
    desc: "",
    link: ""
  },
  {
    key: "国民の休日",
    subKey: "",
    date: 0,
    start: 0,
    desc: "前後が祝日である平日は、国民の休日となり、休日となる。",
    link: "https://ja.wikipedia.org/wiki/%E5%9B%BD%E6%B0%91%E3%81%AE%E4%BC%91%E6%97%A5",
  },
  {
    key: "振替休日",
    subKey: "",
    date: 0,
    start: 0,
    desc: "休日（主に祝祭日）が他の休日（日曜日、他の祝祭日など）と重なった場合、月曜日以降を休日にして休日が減らないようにする制度である。",
    link: "https://ja.wikipedia.org/wiki/%E6%8C%AF%E6%9B%BF%E4%BC%91%E6%97%A5",
  },
  {
    key: "春季皇霊祭",
    subKey: "",
    date: 0,
    start: 0,
    desc: "先祖を祭る日であった。またお彼岸に最も近い戊の日は、社日として氏子が氏神たる神社に参詣し、春は五穀豊穣を祈り、秋は実りある収穫に感謝する習わしがあった。",
    link: "https://ja.wikipedia.org/wiki/%E7%9A%87%E9%9C%8A%E7%A5%AD",
  },
  {
    key: "秋季皇霊祭",
    subKey: "",
    date: 0,
    start: 0,
    desc: "先祖を祭る日であった。またお彼岸に最も近い戊の日は、社日として氏子が氏神たる神社に参詣し、春は五穀豊穣を祈り、秋は実りある収穫に感謝する習わしがあった。",
    link: "https://ja.wikipedia.org/wiki/%E7%9A%87%E9%9C%8A%E7%A5%AD",
  },
  {
    key: "天長節",
    subKey: "",
    date: 0,
    start: 0,
    desc: "天皇誕生日は、慣例により日本の国家の日とされる。昭和23年（1948年）までは、天長節（てんちょうせつ）と呼ばれていた",
    link: "https://ja.wikipedia.org/wiki/%E5%A4%A9%E7%9A%87%E8%AA%95%E7%94%9F%E6%97%A5",
  },
]
